services:
  - type: web
    name: ml-execution-dashboard
    runtime: docker
    region: singapore

    dockerfilePath: ./Dockerfile

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: TIMEZONE
        value: Asia/Kolkata